name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull surajkumar00/ai-customer-support:latest
    - name: Delete Old docker container
      run: sudo docker rm -f ai-customer-support-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name ai-customer-support-container surajkumar00/ai-customer-support