name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      env:
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}  # Pass the API key from GitHub secrets
      run: docker build --build-arg CLOUDFLARE_API_KEY=$CLOUDFLARE_API_KEY -t surajkumar00/ai-customer-support .

    - name: Push to Dockerhub
      run: docker push surajkumar00/ai-customer-support
